import { hashSync } from "bcrypt-ts-edge";
const sampleData = {
  users: [
    {
      name: "Raouf",
      email: "fafa@admin.com",
      password: hashSync("farah2004", 10),
      role: "admin",
    },
    {
      name: "UserRaouf",
      email: "user@user.com",
      password: hashSync("farah2004", 10),
      role: "user",
    },
  ],
  products: [
    {
      name: "قميص بولو مطاطي أنيق",
      slug: "polo-sporting-stretch-shirt",
      category: "قمصان رجالية",
      description: "أسلوب بولو كلاسيكي مع راحة عصرية وممتازة",
      images: [
        "/images/sample-products/p1-1.jpg",
        "/images/sample-products/p1-2.jpg",
      ],
      price: 2500,
      brand: "Polo",
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: "banner-1.jpg",
    },
    {
      name: "قميص بروكس براذرز بأكمام طويلة",
      slug: "brooks-brothers-long-sleeved-shirt",
      category: "قمصان رجالية",
      description: "تصميم أنيق وراحة ممتازة تناسب كل الأوقات",
      images: [
        "/images/sample-products/p2-1.jpg",
        "/images/sample-products/p2-2.jpg",
      ],
      price: 2000,
      brand: "Brooks Brothers",
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: true,
      banner: "banner-2.jpg",
    },
    {
      name: "قميص تومي هيلفيغر كلاسيك فاخر",
      slug: "tommy-hilfiger-classic-fit-dress-shirt",
      category: "قمصان رجالية",
      description: "مزيج مثالي بين الرقي والراحة للمناسبات واليوميات",
      images: [
        "/images/sample-products/p3-1.jpg",
        "/images/sample-products/p3-2.jpg",
      ],
      price: 3700,
      brand: "Tommy Hilfiger",
      rating: 4.9,
      numReviews: 3,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: "قميص كالفن كلاين سليم فيت مطاطي",
      slug: "calvin-klein-slim-fit-stretch-shirt",
      category: "قمصان رجالية",
      description: "تصميم عصري وقماش مرن لمظهر جذاب ورائع",
      images: [
        "/images/sample-products/p4-1.jpg",
        "/images/sample-products/p4-2.jpg",
      ],
      price: 1500,
      brand: "Calvin Klein",
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: "قميص أكسفورد بولو رالف لورين",
      slug: "polo-ralph-lauren-oxford-shirt",
      category: "قمصان رجالية",
      description: "تصميم بولو الأيقوني بقماش أكسفورد فاخر ومريح",
      images: [
        "/images/sample-products/p5-1.jpg",
        "/images/sample-products/p5-2.jpg",
      ],
      price: 2000,
      brand: "Polo",
      rating: 4.7,
      numReviews: 18,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      name: "سترة بولو وردية كلاسيكية مع قبعة",
      slug: "polo-classic-pink-hoodie",
      category: "سترات وسويت شيرت",
      description: "ناعمة وأنيقة ومثالية للأيام الهادئة والمظهر العصري",
      images: [
        "/images/sample-products/p6-1.jpg",
        "/images/sample-products/p6-2.jpg",
      ],
      price: 4000,
      brand: "Polo",
      rating: 4.6,
      numReviews: 12,
      stock: 8,
      isFeatured: true,
      banner: null,
    },
  ],
};

export default sampleData;
